### PR TITLE
allow interpolation of lattices

### PR DESCRIPTION
**Pull request by jacksund**
Extremely minimal addition to the code. For PathFinder's from_endpoints method, we pass an extra keyword such that structures with different lattices can also be interpolated. The default is False in order to match prior behavior.

I don't believe this change merits a unit-test as it's just wrapping functionality located in the pymatgen code.

### CODE REVIEW

**Comment by jacksund** [comment]
@shyuep can you review this addition?

**Comment by shyuep** [comment]
This is fine but I need a unittest for the new functionality (yes I am aware the original interpolation code is in main puymatgen).

**Comment by jacksund** [comment]
gotcha, I'll work on adding one now. Thank you :smile:

**Comment by jacksund** [comment]
@shyuep the new test has been added

**Comment by shyuep** [comment]
THanks.

**Pull request merged**
