### PR TITLE
[WIP] Make MigrationHop MSONable again

### PR DESCRIPTION
**Pull request by mkhorton**
Please add test @jmmshn thank you!

### CODE REVIEW

**Comment by jmmshn** [comment]
So it looks like we are hitting a custom as_dict + from_dict 

https://github.com/materialsproject/pymatgen/blob/dffcac644662d9657d17f872b3c397c5e5a17df7/pymatgen/symmetry/structure.py#L135

**Comment by mkhorton** [comment]
From looking at it, it's not even clear to me that that custom as_dict() is necessary at all.

**Comment by mkhorton** [comment]
That said, why is this an issue upstream?

**Comment by jmmshn** [comment]
OK so sit down for this one...

So right now I think when `MigrationHop.from_dict` getting called, and the parser hits the `symm_structure` it goes into the `structure` field of `SymmetrizedStructure` which then sees the 
`'@class': 'SymmetrizedStructure'` part of the dictionary and tries to run the `SymmetrizedStructure.as_dict` on the `structure` field of serialized dictionary.
 
image

**Comment by jmmshn** [comment]
So the problem right now is
```
# Hop is some MigrationHop object
d = mg.as_dict()
MigrationHop.from_dict(d)  # errors out
MontyDecoder().process_decoded(d['symm_structure']) # errors out
```
The decoding errors out even though it's just a dictionary because when it gets to `d["symm_structure"]["structure"]` it sees a `'@class': 'SymmetrizedStructure` and just freaks out.

That's because this line is absolutely not OK.
https://github.com/materialsproject/pymatgen/blob/dffcac644662d9657d17f872b3c397c5e5a17df7/pymatgen/symmetry/structure.py#L140

**Comment by shyuep** [comment]
This should be fixed in the pymatgen SymmetrizedStructure side, not in the diffusion package.

**Comment by acrutt** [comment]
@jmmshn @mkhorton is there an update on if the necessary fixes for this were implemented in pymatgen? I'm now running into issues because this was never resolved.

**Comment by mkhorton** [comment]
If someone else would like to take over this PR, please do, I think it only needs a test to be able to merge; if I recall I opened this during a debugging session, but I'm not involved in pymatgen-analysis-diffusion so would prefer someone else who is actively using it takes it on.

**Comment by acrutt** [comment]
I can take over writing a test for this but was confused by the follow-up discussion. Is there still an issue with encoding `SymmetrizedStructure` as a dict?

**Comment by acrutt** [comment]
This issues has been resolved in a new PR that was successfully merged: https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion/pull/312

**Comment by mkhorton** [comment]
Fantastic, thanks @acrutt!

**Comment by jmmshn** [comment]
Thanks, @acrutt  I'm on leave for the rest of this month so have been slow with emails.

**Comment by jmmshn** [comment]
So I think the underlying bug was still not fixed in pymatgen.
It's being addressed in a PR now after that all the code should work as expected.

**Comment by jmmshn** [comment]
@acrutt if tried to serialize->deserialize with `host_symm_structure` it throws an error right?

**Comment by acrutt** [comment]
I'm not familiar with that part of the issue. When I create a MigrationHop with the `host_symm_struct` attribute initialized, the `.as_dict()` method works for me. I'm using pymatgen version 2022.7.19.

**Comment by jmmshn** [comment]
So the bug only triggers a problem if you read from a db or read via `loadfn` due to the order in which things load.

If you see a `'@class': 'SymmetrizedStructure'` after you run `hop.as_dict()` then the program will error out when you `dumpfn` -> `loadfn` any object that contains the hop.

**Pull request closed without merging**
