### PR TITLE
Make MigrationHop MSONable again

### PR DESCRIPTION
**Pull request by acrutt**
Taking over a previous pull request that was abandoned: https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion/pull/264

### CODE REVIEW

**Comment by shyuep** [comment]
Pls fix the test errors. The linting errors can be dealt with later, but the unittest must pass.

**Comment by shyuep** [comment]
Pls merge the latest master. A lot of the problems will disappear.

**Comment by shyuep** [comment]
The tests fail because there are changes in your PR with host_symm_structure. These need to be fixed.

**Comment by acrutt** [comment]
@shyuep would it be possible to release an updated version of pymatgen-analysis-diffusion with this change on PyPi? I am working on code in emmet that depends on this patch.

**Comment by shyuep** [comment]
Done.

**Comment by acrutt** [comment]
Great! Thank you so much @shyuep for your responsiveness in getting this fix addressed in a timely manner.

**Pull request merged**
